// Auto-generated by build_analysis.py — NEET-PG PYQ analysis.
window.NEET_DATA = {
 "meta": {
  "generated_years": [
   "2010",
   "2011",
   "2012",
   "2013",
   "2014",
   "2016",
   "2017",
   "2018",
   "2019",
   "2020",
   "2021",
   "2022",
   "2023",
   "2024",
   "2025"
  ],
  "stats_years": [
   "2010",
   "2011",
   "2012",
   "2013",
   "2014",
   "2017",
   "2018",
   "2019",
   "2020",
   "2021",
   "2022",
   "2023",
   "2024",
   "2025"
  ],
  "excluded_years": [
   "2016"
  ],
  "grand_total_questions": 3623,
  "grand_stats_questions": 3323,
  "grand_classified": 2304,
  "grand_unclassified": 1019,
  "denominators_by_year": {
   "2010": {
    "parsed_questions": 300,
    "classification_rate": 300,
    "subject_distribution": 212,
    "trend_statistics": 300
   },
   "2011": {
    "parsed_questions": 296,
    "classification_rate": 296,
    "subject_distribution": 207,
    "trend_statistics": 296
   },
   "2012": {
    "parsed_questions": 200,
    "classification_rate": 200,
    "subject_distribution": 124,
    "trend_statistics": 200
   },
   "2013": {
    "parsed_questions": 200,
    "classification_rate": 200,
    "subject_distribution": 128,
    "trend_statistics": 200
   },
   "2014": {
    "parsed_questions": 200,
    "classification_rate": 200,
    "subject_distribution": 125,
    "trend_statistics": 200
   },
   "2016": {
    "parsed_questions": 300,
    "classification_rate": 0,
    "subject_distribution": 0,
    "trend_statistics": 0
   },
   "2017": {
    "parsed_questions": 300,
    "classification_rate": 300,
    "subject_distribution": 188,
    "trend_statistics": 300
   },
   "2018": {
    "parsed_questions": 295,
    "classification_rate": 295,
    "subject_distribution": 188,
    "trend_statistics": 295
   },
   "2019": {
    "parsed_questions": 293,
    "classification_rate": 293,
    "subject_distribution": 182,
    "trend_statistics": 293
   },
   "2020": {
    "parsed_questions": 299,
    "classification_rate": 299,
    "subject_distribution": 217,
    "trend_statistics": 299
   },
   "2021": {
    "parsed_questions": 206,
    "classification_rate": 206,
    "subject_distribution": 167,
    "trend_statistics": 206
   },
   "2022": {
    "parsed_questions": 173,
    "classification_rate": 173,
    "subject_distribution": 142,
    "trend_statistics": 173
   },
   "2023": {
    "parsed_questions": 194,
    "classification_rate": 194,
    "subject_distribution": 154,
    "trend_statistics": 194
   },
   "2024": {
    "parsed_questions": 168,
    "classification_rate": 168,
    "subject_distribution": 113,
    "trend_statistics": 168
   },
   "2025": {
    "parsed_questions": 199,
    "classification_rate": 199,
    "subject_distribution": 157,
    "trend_statistics": 199
   }
  },
  "exam_date_2026": "2026-08-30"
 },
 "sections": {
  "Pre-Clinical": [
   "Anatomy",
   "Physiology",
   "Biochemistry"
  ],
  "Para-Clinical": [
   "Pathology",
   "Pharmacology",
   "Microbiology",
   "Forensic Medicine",
   "PSM"
  ],
  "Clinical": [
   "Medicine",
   "Surgery",
   "Obstetrics & Gynaecology",
   "Paediatrics",
   "Orthopaedics",
   "Radiology",
   "Anaesthesia",
   "Psychiatry",
   "Dermatology",
   "Ophthalmology",
   "ENT"
  ]
 },
 "subjects": [
  "Anatomy",
  "Physiology",
  "Biochemistry",
  "Pathology",
  "Pharmacology",
  "Microbiology",
  "Forensic Medicine",
  "PSM",
  "Medicine",
  "Surgery",
  "Obstetrics & Gynaecology",
  "Paediatrics",
  "Orthopaedics",
  "Radiology",
  "Anaesthesia",
  "Psychiatry",
  "Dermatology",
  "Ophthalmology",
  "ENT"
 ],
 "subject_totals": {
  "Anatomy": 244,
  "Physiology": 33,
  "Biochemistry": 142,
  "Pathology": 228,
  "Pharmacology": 201,
  "Microbiology": 179,
  "Forensic Medicine": 57,
  "PSM": 36,
  "Medicine": 311,
  "Surgery": 95,
  "Obstetrics & Gynaecology": 199,
  "Paediatrics": 77,
  "Orthopaedics": 101,
  "Radiology": 105,
  "Anaesthesia": 53,
  "Psychiatry": 56,
  "Dermatology": 53,
  "Ophthalmology": 78,
  "ENT": 56
 },
 "topic_totals": {
  "Anatomy": {
   "General": 128,
   "Lower Limb": 15,
   "Head & Neck": 37,
   "Thorax": 7,
   "Neuroanatomy": 13,
   "Histology": 17,
   "Upper Limb": 13,
   "Embryology": 3,
   "Abdomen & Pelvis": 11
  },
  "Physiology": {
   "Cardiovascular": 10,
   "GI": 1,
   "Respiratory": 3,
   "Nerve & Muscle": 8,
   "CNS": 4,
   "General": 6,
   "Renal": 1
  },
  "Biochemistry": {
   "Vitamins & Minerals": 40,
   "Enzymes": 34,
   "Molecular Biology": 33,
   "Metabolism": 22,
   "General": 13
  },
  "Pathology": {
   "Neoplasia": 134,
   "Inflammation & Immunity": 22,
   "Haematology": 30,
   "General": 33,
   "Systemic Pathology": 9
  },
  "Pharmacology": {
   "General": 103,
   "CNS": 4,
   "Cardiovascular": 24,
   "Antimicrobials": 30,
   "Autonomic": 28,
   "Chemotherapy": 7,
   "Pharmacokinetics": 5
  },
  "Microbiology": {
   "Immunology": 30,
   "Bacteriology": 83,
   "Virology": 36,
   "General": 15,
   "Mycology": 6,
   "Parasitology": 9
  },
  "Forensic Medicine": {
   "Medical Law": 10,
   "Toxicology": 17,
   "Asphyxia & Trauma": 13,
   "General": 8,
   "Thanatology": 9
  },
  "PSM": {
   "Health Programs": 2,
   "General": 9,
   "Epidemiology": 18,
   "Biostatistics": 5,
   "Nutrition": 1,
   "Communicable Disease": 1
  },
  "Medicine": {
   "General": 116,
   "Cardiology": 36,
   "Neurology": 19,
   "Infectious Disease": 32,
   "Endocrinology": 34,
   "Pulmonology": 12,
   "Gastroenterology": 35,
   "Nephrology": 13,
   "Rheumatology": 14
  },
  "Surgery": {
   "General": 35,
   "GI Surgery": 19,
   "Surgical Oncology": 7,
   "Trauma & Burns": 21,
   "Vascular": 9,
   "Hepatobiliary": 4
  },
  "Obstetrics & Gynaecology": {
   "Gynae-Oncology": 13,
   "Antenatal": 120,
   "Contraception & Menstrual": 20,
   "General": 19,
   "Labour & Delivery": 20,
   "Obstetric Emergencies": 7
  },
  "Paediatrics": {
   "General": 38,
   "Neonatology": 20,
   "Congenital": 10,
   "Immunization": 1,
   "Growth & Development": 3,
   "Nutrition": 5
  },
  "Orthopaedics": {
   "General": 16,
   "Joints": 32,
   "Bone Tumours": 6,
   "Fractures": 37,
   "Spine": 8,
   "Infections": 2
  },
  "Radiology": {
   "General": 11,
   "X-ray": 44,
   "Contrast & Nuclear": 18,
   "CT & MRI": 24,
   "Ultrasound": 8
  },
  "Anaesthesia": {
   "Muscle Relaxants": 11,
   "Regional": 7,
   "Inhalational Agents": 4,
   "General": 14,
   "Airway": 17
  },
  "Psychiatry": {
   "Mood Disorders": 26,
   "Psychosis": 20,
   "General": 5,
   "Anxiety": 5
  },
  "Dermatology": {
   "Infections": 8,
   "General": 31,
   "Papulosquamous": 5,
   "Tumours": 5,
   "Vesiculobullous": 4
  },
  "Ophthalmology": {
   "Retina": 16,
   "Cornea & Anterior": 19,
   "Neuro-ophthalmology": 8,
   "Cataract & Lens": 17,
   "General": 9,
   "Glaucoma": 9
  },
  "ENT": {
   "Rhinology": 15,
   "Otology": 29,
   "Laryngology": 11,
   "General": 1
  }
 },
 "years": {
  "2010": {
   "counts": {
    "Anatomy": 17,
    "Physiology": 1,
    "Biochemistry": 8,
    "Pathology": 23,
    "Pharmacology": 18,
    "Microbiology": 16,
    "Forensic Medicine": 3,
    "PSM": 7,
    "Medicine": 30,
    "Surgery": 13,
    "Obstetrics & Gynaecology": 19,
    "Paediatrics": 7,
    "Orthopaedics": 11,
    "Radiology": 14,
    "Anaesthesia": 3,
    "Psychiatry": 7,
    "Dermatology": 5,
    "Ophthalmology": 6,
    "ENT": 4
   },
   "total_questions": 300,
   "classified": 212,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 300,
    "classification_rate": 300,
    "subject_distribution": 212,
    "trend_statistics": 300
   },
   "extraction_quality": {
    "high": 300,
    "medium": 0,
    "low": 0
   },
   "image_dependent_questions": 13,
   "source_pages": {
    "NEET-PG-2010-Question-Paper.pdf": 79
   },
   "files": {
    "qp": [
     "NEET-PG-2010-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2010-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2011": {
   "counts": {
    "Anatomy": 32,
    "Physiology": 2,
    "Biochemistry": 10,
    "Pathology": 16,
    "Pharmacology": 22,
    "Microbiology": 20,
    "Forensic Medicine": 2,
    "PSM": 5,
    "Medicine": 28,
    "Surgery": 9,
    "Obstetrics & Gynaecology": 15,
    "Paediatrics": 5,
    "Orthopaedics": 8,
    "Radiology": 6,
    "Anaesthesia": 8,
    "Psychiatry": 6,
    "Dermatology": 2,
    "Ophthalmology": 6,
    "ENT": 5
   },
   "total_questions": 296,
   "classified": 207,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 296,
    "classification_rate": 296,
    "subject_distribution": 207,
    "trend_statistics": 296
   },
   "extraction_quality": {
    "high": 296,
    "medium": 0,
    "low": 0
   },
   "image_dependent_questions": 16,
   "source_pages": {
    "NEET-PG-2011-Question-Paper.pdf": 77
   },
   "files": {
    "qp": [
     "NEET-PG-2011-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2011-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2012": {
   "counts": {
    "Anatomy": 19,
    "Physiology": 2,
    "Biochemistry": 10,
    "Pathology": 11,
    "Pharmacology": 6,
    "Microbiology": 10,
    "Forensic Medicine": 5,
    "PSM": 1,
    "Medicine": 12,
    "Surgery": 1,
    "Obstetrics & Gynaecology": 8,
    "Paediatrics": 5,
    "Orthopaedics": 7,
    "Radiology": 5,
    "Anaesthesia": 4,
    "Psychiatry": 3,
    "Dermatology": 3,
    "Ophthalmology": 10,
    "ENT": 2
   },
   "total_questions": 200,
   "classified": 124,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 200,
    "classification_rate": 200,
    "subject_distribution": 124,
    "trend_statistics": 200
   },
   "extraction_quality": {
    "high": 200,
    "medium": 0,
    "low": 0
   },
   "image_dependent_questions": 7,
   "source_pages": {
    "NEET-PG-2012-Question-Paper.pdf": 52
   },
   "files": {
    "qp": [
     "NEET-PG-2012-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2012-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2013": {
   "counts": {
    "Anatomy": 15,
    "Physiology": 2,
    "Biochemistry": 7,
    "Pathology": 13,
    "Pharmacology": 7,
    "Microbiology": 10,
    "Forensic Medicine": 2,
    "PSM": 0,
    "Medicine": 19,
    "Surgery": 6,
    "Obstetrics & Gynaecology": 6,
    "Paediatrics": 4,
    "Orthopaedics": 3,
    "Radiology": 7,
    "Anaesthesia": 6,
    "Psychiatry": 6,
    "Dermatology": 6,
    "Ophthalmology": 6,
    "ENT": 3
   },
   "total_questions": 200,
   "classified": 128,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 200,
    "classification_rate": 200,
    "subject_distribution": 128,
    "trend_statistics": 200
   },
   "extraction_quality": {
    "high": 200,
    "medium": 0,
    "low": 0
   },
   "image_dependent_questions": 7,
   "source_pages": {
    "NEET-PG-2013-Question-Paper.pdf": 51
   },
   "files": {
    "qp": [
     "NEET-PG-2013-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2013-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2014": {
   "counts": {
    "Anatomy": 9,
    "Physiology": 0,
    "Biochemistry": 8,
    "Pathology": 12,
    "Pharmacology": 12,
    "Microbiology": 20,
    "Forensic Medicine": 2,
    "PSM": 4,
    "Medicine": 13,
    "Surgery": 4,
    "Obstetrics & Gynaecology": 7,
    "Paediatrics": 5,
    "Orthopaedics": 6,
    "Radiology": 7,
    "Anaesthesia": 4,
    "Psychiatry": 3,
    "Dermatology": 4,
    "Ophthalmology": 1,
    "ENT": 4
   },
   "total_questions": 200,
   "classified": 125,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 200,
    "classification_rate": 200,
    "subject_distribution": 125,
    "trend_statistics": 200
   },
   "extraction_quality": {
    "high": 199,
    "medium": 1,
    "low": 0
   },
   "image_dependent_questions": 2,
   "source_pages": {
    "NEET-PG-2014-Question-Paper.pdf": 51
   },
   "files": {
    "qp": [
     "NEET-PG-2014-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2014-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2016": {
   "counts": {
    "Anatomy": 0,
    "Physiology": 0,
    "Biochemistry": 0,
    "Pathology": 0,
    "Pharmacology": 0,
    "Microbiology": 0,
    "Forensic Medicine": 0,
    "PSM": 0,
    "Medicine": 0,
    "Surgery": 0,
    "Obstetrics & Gynaecology": 0,
    "Paediatrics": 0,
    "Orthopaedics": 0,
    "Radiology": 0,
    "Anaesthesia": 0,
    "Psychiatry": 0,
    "Dermatology": 0,
    "Ophthalmology": 0,
    "ENT": 0
   },
   "total_questions": 300,
   "classified": 0,
   "stats_excluded": true,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 300,
    "classification_rate": 0,
    "subject_distribution": 0,
    "trend_statistics": 0
   },
   "extraction_quality": {
    "high": 222,
    "medium": 78,
    "low": 0
   },
   "image_dependent_questions": 4,
   "source_pages": {
    "NEET-PG-2016-Question-Paper.pdf": 325
   },
   "files": {
    "qp": [
     "NEET-PG-2016-Question-Paper.pdf"
    ],
    "sol": [],
    "key": [
     "NEET-PG-2016-Answer-Key.pdf"
    ]
   }
  },
  "2017": {
   "counts": {
    "Anatomy": 22,
    "Physiology": 3,
    "Biochemistry": 13,
    "Pathology": 20,
    "Pharmacology": 19,
    "Microbiology": 14,
    "Forensic Medicine": 3,
    "PSM": 3,
    "Medicine": 20,
    "Surgery": 4,
    "Obstetrics & Gynaecology": 21,
    "Paediatrics": 6,
    "Orthopaedics": 9,
    "Radiology": 8,
    "Anaesthesia": 6,
    "Psychiatry": 3,
    "Dermatology": 3,
    "Ophthalmology": 5,
    "ENT": 6
   },
   "total_questions": 300,
   "classified": 188,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 300,
    "classification_rate": 300,
    "subject_distribution": 188,
    "trend_statistics": 300
   },
   "extraction_quality": {
    "high": 300,
    "medium": 0,
    "low": 0
   },
   "image_dependent_questions": 33,
   "source_pages": {
    "NEET-PG-2017-Question-Paper.pdf": 90
   },
   "files": {
    "qp": [
     "NEET-PG-2017-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2017-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2018": {
   "counts": {
    "Anatomy": 20,
    "Physiology": 3,
    "Biochemistry": 14,
    "Pathology": 19,
    "Pharmacology": 19,
    "Microbiology": 13,
    "Forensic Medicine": 3,
    "PSM": 3,
    "Medicine": 21,
    "Surgery": 4,
    "Obstetrics & Gynaecology": 22,
    "Paediatrics": 7,
    "Orthopaedics": 9,
    "Radiology": 7,
    "Anaesthesia": 6,
    "Psychiatry": 3,
    "Dermatology": 3,
    "Ophthalmology": 5,
    "ENT": 7
   },
   "total_questions": 295,
   "classified": 188,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 295,
    "classification_rate": 295,
    "subject_distribution": 188,
    "trend_statistics": 295
   },
   "extraction_quality": {
    "high": 294,
    "medium": 1,
    "low": 0
   },
   "image_dependent_questions": 33,
   "source_pages": {
    "NEET-PG-2018-Question-Paper.pdf": 88
   },
   "files": {
    "qp": [
     "NEET-PG-2018-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2018-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2019": {
   "counts": {
    "Anatomy": 22,
    "Physiology": 5,
    "Biochemistry": 13,
    "Pathology": 13,
    "Pharmacology": 26,
    "Microbiology": 13,
    "Forensic Medicine": 6,
    "PSM": 4,
    "Medicine": 19,
    "Surgery": 5,
    "Obstetrics & Gynaecology": 16,
    "Paediatrics": 3,
    "Orthopaedics": 9,
    "Radiology": 7,
    "Anaesthesia": 5,
    "Psychiatry": 4,
    "Dermatology": 7,
    "Ophthalmology": 3,
    "ENT": 2
   },
   "total_questions": 293,
   "classified": 182,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 293,
    "classification_rate": 293,
    "subject_distribution": 182,
    "trend_statistics": 293
   },
   "extraction_quality": {
    "high": 292,
    "medium": 1,
    "low": 0
   },
   "image_dependent_questions": 56,
   "source_pages": {
    "NEET-PG-2019-Question-Paper.pdf": 100
   },
   "files": {
    "qp": [
     "NEET-PG-2019-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2019-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2020": {
   "counts": {
    "Anatomy": 18,
    "Physiology": 2,
    "Biochemistry": 17,
    "Pathology": 22,
    "Pharmacology": 19,
    "Microbiology": 19,
    "Forensic Medicine": 6,
    "PSM": 2,
    "Medicine": 31,
    "Surgery": 10,
    "Obstetrics & Gynaecology": 20,
    "Paediatrics": 8,
    "Orthopaedics": 6,
    "Radiology": 11,
    "Anaesthesia": 3,
    "Psychiatry": 5,
    "Dermatology": 3,
    "Ophthalmology": 9,
    "ENT": 6
   },
   "total_questions": 299,
   "classified": 217,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 299,
    "classification_rate": 299,
    "subject_distribution": 217,
    "trend_statistics": 299
   },
   "extraction_quality": {
    "high": 299,
    "medium": 0,
    "low": 0
   },
   "image_dependent_questions": 67,
   "source_pages": {
    "NEET-PG-2020-Question-Paper.pdf": 99
   },
   "files": {
    "qp": [
     "NEET-PG-2020-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2020-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2021": {
   "counts": {
    "Anatomy": 19,
    "Physiology": 2,
    "Biochemistry": 9,
    "Pathology": 15,
    "Pharmacology": 10,
    "Microbiology": 13,
    "Forensic Medicine": 3,
    "PSM": 3,
    "Medicine": 22,
    "Surgery": 11,
    "Obstetrics & Gynaecology": 16,
    "Paediatrics": 8,
    "Orthopaedics": 8,
    "Radiology": 10,
    "Anaesthesia": 1,
    "Psychiatry": 4,
    "Dermatology": 5,
    "Ophthalmology": 6,
    "ENT": 2
   },
   "total_questions": 206,
   "classified": 167,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 206,
    "classification_rate": 206,
    "subject_distribution": 167,
    "trend_statistics": 206
   },
   "extraction_quality": {
    "high": 206,
    "medium": 0,
    "low": 0
   },
   "image_dependent_questions": 45,
   "source_pages": {
    "NEET-PG-2021-Question-Paper.pdf": 83
   },
   "files": {
    "qp": [
     "NEET-PG-2021-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2021-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2022": {
   "counts": {
    "Anatomy": 11,
    "Physiology": 1,
    "Biochemistry": 9,
    "Pathology": 11,
    "Pharmacology": 17,
    "Microbiology": 8,
    "Forensic Medicine": 6,
    "PSM": 0,
    "Medicine": 23,
    "Surgery": 7,
    "Obstetrics & Gynaecology": 22,
    "Paediatrics": 6,
    "Orthopaedics": 5,
    "Radiology": 5,
    "Anaesthesia": 1,
    "Psychiatry": 2,
    "Dermatology": 2,
    "Ophthalmology": 4,
    "ENT": 2
   },
   "total_questions": 173,
   "classified": 142,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 173,
    "classification_rate": 173,
    "subject_distribution": 142,
    "trend_statistics": 173
   },
   "extraction_quality": {
    "high": 173,
    "medium": 0,
    "low": 0
   },
   "image_dependent_questions": 61,
   "source_pages": {
    "NEET-PG-2022-Question-Paper.pdf": 71
   },
   "files": {
    "qp": [
     "NEET-PG-2022-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2022-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2023": {
   "counts": {
    "Anatomy": 9,
    "Physiology": 5,
    "Biochemistry": 5,
    "Pathology": 23,
    "Pharmacology": 12,
    "Microbiology": 12,
    "Forensic Medicine": 5,
    "PSM": 2,
    "Medicine": 29,
    "Surgery": 8,
    "Obstetrics & Gynaecology": 10,
    "Paediatrics": 5,
    "Orthopaedics": 5,
    "Radiology": 6,
    "Anaesthesia": 0,
    "Psychiatry": 3,
    "Dermatology": 3,
    "Ophthalmology": 8,
    "ENT": 4
   },
   "total_questions": 194,
   "classified": 154,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 194,
    "classification_rate": 194,
    "subject_distribution": 154,
    "trend_statistics": 194
   },
   "extraction_quality": {
    "high": 193,
    "medium": 1,
    "low": 0
   },
   "image_dependent_questions": 57,
   "source_pages": {
    "NEET-PG-2023-Question-Paper.pdf": 69
   },
   "files": {
    "qp": [
     "NEET-PG-2023-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2023-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2024": {
   "counts": {
    "Anatomy": 15,
    "Physiology": 2,
    "Biochemistry": 9,
    "Pathology": 7,
    "Pharmacology": 7,
    "Microbiology": 2,
    "Forensic Medicine": 8,
    "PSM": 0,
    "Medicine": 17,
    "Surgery": 8,
    "Obstetrics & Gynaecology": 6,
    "Paediatrics": 4,
    "Orthopaedics": 9,
    "Radiology": 5,
    "Anaesthesia": 2,
    "Psychiatry": 2,
    "Dermatology": 1,
    "Ophthalmology": 6,
    "ENT": 3
   },
   "total_questions": 168,
   "classified": 113,
   "stats_excluded": false,
   "recall_source": false,
   "denominators": {
    "parsed_questions": 168,
    "classification_rate": 168,
    "subject_distribution": 113,
    "trend_statistics": 168
   },
   "extraction_quality": {
    "high": 162,
    "medium": 5,
    "low": 1
   },
   "image_dependent_questions": 52,
   "source_pages": {
    "NEET-PG-2024-Shift-1-Question-Paper.pdf": 58,
    "NEET-PG-2024-Shift-2-Question-Paper.pdf": 10
   },
   "files": {
    "qp": [
     "NEET-PG-2024-Shift-1-Question-Paper.pdf",
     "NEET-PG-2024-Shift-2-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2024-Shift-1-Solutions.pdf",
     "NEET-PG-2024-Shift-2-Solutions.pdf"
    ],
    "key": []
   }
  },
  "2025": {
   "counts": {
    "Anatomy": 16,
    "Physiology": 3,
    "Biochemistry": 10,
    "Pathology": 23,
    "Pharmacology": 7,
    "Microbiology": 9,
    "Forensic Medicine": 3,
    "PSM": 2,
    "Medicine": 27,
    "Surgery": 5,
    "Obstetrics & Gynaecology": 11,
    "Paediatrics": 4,
    "Orthopaedics": 6,
    "Radiology": 7,
    "Anaesthesia": 4,
    "Psychiatry": 5,
    "Dermatology": 6,
    "Ophthalmology": 3,
    "ENT": 6
   },
   "total_questions": 199,
   "classified": 157,
   "stats_excluded": false,
   "recall_source": true,
   "denominators": {
    "parsed_questions": 199,
    "classification_rate": 199,
    "subject_distribution": 157,
    "trend_statistics": 199
   },
   "extraction_quality": {
    "high": 198,
    "medium": 1,
    "low": 0
   },
   "image_dependent_questions": 40,
   "source_pages": {
    "NEET-PG-2025-Recall-Questions.md": null
   },
   "files": {
    "qp": [
     "NEET-PG-2025-Question-Paper.pdf"
    ],
    "sol": [
     "NEET-PG-2025-Solutions.pdf"
    ],
    "key": [],
    "recall": [
     "NEET-PG-2025-Recall-Questions.md"
    ]
   }
  }
 },
 "predictions": {
  "source": "Dr Ganga's Master Medicine — 180 high-yield topic forecast for NEET-PG 2026",
  "total_topics": 180,
  "total_repeats": 605,
  "priority_counts": {
   "High": 131,
   "Moderate": 43,
   "Low": 6
  },
  "subjects": {
   "Anatomy": {
    "declared": 7,
    "combined": 19,
    "topics": [
     {
      "topic": "NERVES",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Oocyte , Fertilization, Cortical reaction",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Umbilicus",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Abductor Pollicis Brevis",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Aortic Arches",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Cerebellum",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Muscles of Mastication",
      "times": 2,
      "priority": "Moderate"
     }
    ]
   },
   "Physiology": {
    "declared": 8,
    "combined": 16,
    "topics": [
     {
      "topic": "Action Potential Curve",
      "times": 2,
      "priority": "High"
     },
     {
      "topic": "GLUT Transporters",
      "times": 2,
      "priority": "High"
     },
     {
      "topic": "JVP waves",
      "times": 2,
      "priority": "High"
     },
     {
      "topic": "Pacinian Corpuscle",
      "times": 2,
      "priority": "High"
     },
     {
      "topic": "Post-gastrectomy / ileal & jejunal resection",
      "times": 2,
      "priority": "High"
     },
     {
      "topic": "Respiratory Distress Syndrome",
      "times": 2,
      "priority": "High"
     },
     {
      "topic": "Resting Membrane Potential",
      "times": 2,
      "priority": "High"
     },
     {
      "topic": "Sensory fibres",
      "times": 2,
      "priority": "High"
     }
    ]
   },
   "Biochemistry": {
    "declared": 9,
    "combined": 39,
    "topics": [
     {
      "topic": "Vitamins",
      "times": 15,
      "priority": "High"
     },
     {
      "topic": "Lysosomal storage disorder",
      "times": 6,
      "priority": "High"
     },
     {
      "topic": "Glycogen storage disorders",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Alkaptonuria",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Familial hypercholesterolaemia",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Homocystinuria",
      "times": 2,
      "priority": "High"
     },
     {
      "topic": "Metabolic cycles – insulin:glucagon ratio",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Inhibition",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Minerals",
      "times": 2,
      "priority": "Moderate"
     }
    ]
   },
   "Pathology": {
    "declared": 14,
    "combined": 61,
    "topics": [
     {
      "topic": "Genetics and syndrome",
      "times": 8,
      "priority": "High"
     },
     {
      "topic": "Leukaemia",
      "times": 8,
      "priority": "High"
     },
     {
      "topic": "Intestinal disorders",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Lymphoma",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Carcinoma lung and thymoma",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Disorders of Haemoglobin",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Glomerular diseases",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Thyroid",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Tumors",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Coagulation disorders",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Inflammation",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Iron deficiency anaemia",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Macrocytic anaemia",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Multiple Myeloma and Amyloid",
      "times": 3,
      "priority": "High"
     }
    ]
   },
   "Pharmacology": {
    "declared": 12,
    "combined": 56,
    "topics": [
     {
      "topic": "Antihypertensives",
      "times": 7,
      "priority": "High"
     },
     {
      "topic": "Antimuscarinic",
      "times": 7,
      "priority": "High"
     },
     {
      "topic": "Antiarrhythmic",
      "times": 6,
      "priority": "High"
     },
     {
      "topic": "Anti TB",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Anticoagulants and Fibrinolytics",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Antiemetics",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "NSAIDs",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Pharmacokinetics and Pharmacodynamics",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Antifungal",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Antimalarials",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Antimicrobials",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Antiparkinsons",
      "times": 3,
      "priority": "High"
     }
    ]
   },
   "Microbiology": {
    "declared": 9,
    "combined": 30,
    "topics": [
     {
      "topic": "Nematodes",
      "times": 6,
      "priority": "High"
     },
     {
      "topic": "Neisseria gonorrhoeae",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Candidiasis",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Leptospirosis",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Neisseria meningitidis",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Vibrio",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Hemoflagellates",
      "times": 3,
      "priority": "Moderate"
     },
     {
      "topic": "Malaria",
      "times": 3,
      "priority": "Moderate"
     },
     {
      "topic": "Bacterial structure",
      "times": 2,
      "priority": "Moderate"
     }
    ]
   },
   "Forensic Medicine": {
    "declared": 8,
    "combined": 29,
    "topics": [
     {
      "topic": "Postmortem",
      "times": 7,
      "priority": "High"
     },
     {
      "topic": "Age estimation, identification",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Arsenic",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Asphyxial Death",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Barberio test",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Datura poisoning",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Autopsy techniques",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "BNS SECTIONS",
      "times": 2,
      "priority": "Moderate"
     }
    ]
   },
   "Medicine": {
    "declared": 15,
    "combined": 60,
    "topics": [
     {
      "topic": "ECG, arrhythmias & heart blocks",
      "times": 9,
      "priority": "High"
     },
     {
      "topic": "ABG and RTA",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Diabetes – DKA and HHS",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Pituitary disorders – DI and SIADH",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "HIV",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Valvular heart disease",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Vasculitis",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Cirrhosis and its complications (SBP, Child–Pugh, variceal bleed)",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Coronary artery disease",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Disorders of Aorta",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Electrolyte disorders",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Heart failure",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "JVP",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Malabsorption disorders",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Pleural disease",
      "times": 3,
      "priority": "High"
     }
    ]
   },
   "Surgery": {
    "declared": 16,
    "combined": 56,
    "topics": [
     {
      "topic": "Breast Cancer",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Inguinal hernia / hernia",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Bladder Carcinoma",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Oral Cavity Cancer",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Penile Carcinoma",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Triage / trauma",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Aortic Dissection",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Cystourethroscope",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Fistula in Ano",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Glasgow Coma Scale",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Hollow Viscus Perforation",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Hydatid cyst",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Oesophageal Varices",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Peripheral arterial disease / Leriche’s syndrome / aorto-iliac disease",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Rectal Carcinoma",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Subarachnoid haemorrhage",
      "times": 3,
      "priority": "High"
     }
    ]
   },
   "Obstetrics & Gynaecology": {
    "declared": 17,
    "combined": 66,
    "topics": [
     {
      "topic": "Endometriosis / endometrioma",
      "times": 6,
      "priority": "High"
     },
     {
      "topic": "Fibroids",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Hysteroscopy",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Mullerian anomalies",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Breech & vertex presentation / persistent occipito-posterior",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "High-risk pregnancy / mother on anticoagulant",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Normal labour / partograph",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Postpartum haemorrhage",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Pre eclampsia",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Prolapse",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Amniotic fluid embolism / oligohydramnios / polyhydramnios",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "C-SECTION indications",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Cervical Carcinoma",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Ectopic pregnancy",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Gestational Age assessment",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Gestational / pregestational diabetes mellitus",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "HELLP syndrome",
      "times": 3,
      "priority": "High"
     }
    ]
   },
   "Paediatrics": {
    "declared": 8,
    "combined": 27,
    "topics": [
     {
      "topic": "Intestinal disorders",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Malnutrition",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Measles",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Congenital infections",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Growth charts and curves",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Nephrotic syndrome",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Bladder exstrophy",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Diphtheria",
      "times": 2,
      "priority": "Moderate"
     }
    ]
   },
   "Orthopaedics": {
    "declared": 7,
    "combined": 19,
    "topics": [
     {
      "topic": "Knee",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Giant cell tumour (osteoclastoma)",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Supracondylar fracture of humerus",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Ankle",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Fat Embolism",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Hip",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Osteoporosis",
      "times": 2,
      "priority": "Moderate"
     }
    ]
   },
   "PSM": {
    "declared": 11,
    "combined": 39,
    "topics": [
     {
      "topic": "Biomedical waste management",
      "times": 6,
      "priority": "High"
     },
     {
      "topic": "Parametric test",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Vitamin deficiency",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Case-control / cohort study",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Disaster management / disaster cycle",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Kata thermometer",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Vaccines / CI for live vaccine / immunisation schedule",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Varicella",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "ASHA",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Coefficient of regression / variation",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Demography / demographic cycle",
      "times": 2,
      "priority": "Moderate"
     }
    ]
   },
   "Psychiatry": {
    "declared": 6,
    "combined": 15,
    "topics": [
     {
      "topic": "Alcohol/Wernicke's",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Postpartum Blues",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Cocaine",
      "times": 2,
      "priority": "High"
     },
     {
      "topic": "Depression",
      "times": 2,
      "priority": "High"
     },
     {
      "topic": "Panic disorder",
      "times": 2,
      "priority": "High"
     },
     {
      "topic": "ADHD",
      "times": 2,
      "priority": "Low"
     }
    ]
   },
   "Dermatology": {
    "declared": 7,
    "combined": 13,
    "topics": [
     {
      "topic": "Acne Vulgaris",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Kerion, Favus",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Leprosy",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Pemphigus Vulgaris",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Psoriasis",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Syphilis",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Acanthosis Nigricans",
      "times": 1,
      "priority": "Low"
     }
    ]
   },
   "Ophthalmology": {
    "declared": 7,
    "combined": 20,
    "topics": [
     {
      "topic": "Visual Pathway Defects",
      "times": 6,
      "priority": "High"
     },
     {
      "topic": "Glaucoma - Drugs",
      "times": 5,
      "priority": "High"
     },
     {
      "topic": "Astigmatism",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Diabetic Retinopathy",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Retinoblastoma",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Uvea -Acute Anterior Uveitis",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Acanthamoeba Keratitis",
      "times": 1,
      "priority": "Low"
     }
    ]
   },
   "ENT": {
    "declared": 7,
    "combined": 15,
    "topics": [
     {
      "topic": "Inner Ear",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Atrophic Rhinitis",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Ear-Nerve Supply",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Nasopharyngeal Angiofibroma",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Otitis Media",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Rinne's Test",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Tonsil",
      "times": 2,
      "priority": "Moderate"
     }
    ]
   },
   "Radiology": {
    "declared": 7,
    "combined": 13,
    "topics": [
     {
      "topic": "Radiation therapy",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Barium Studies",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Craniopharyngioma",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Subarachnoid haemorrhage",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "TAPVC",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "ARDS",
      "times": 1,
      "priority": "Low"
     },
     {
      "topic": "Bowel Obstruction",
      "times": 1,
      "priority": "Low"
     }
    ]
   },
   "Anaesthesia": {
    "declared": 5,
    "combined": 12,
    "topics": [
     {
      "topic": "ACLS",
      "times": 4,
      "priority": "High"
     },
     {
      "topic": "Capnography",
      "times": 3,
      "priority": "High"
     },
     {
      "topic": "Malignant Hyperthermia",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "Muscle Relaxants",
      "times": 2,
      "priority": "Moderate"
     },
     {
      "topic": "EMLA patch (methaemoglobinaemia)",
      "times": 1,
      "priority": "Low"
     }
    ]
   }
  }
 }
};
